[project]
name = "ReassessDTR"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-64"]

[dependencies]
python = "3.9.*"
pytorch = {version = ">=2.0.1", channel = "pytorch"}
matplotlib = ">=3.8.4,<3.9"
seaborn = ">=0.13.2,<0.14"
pandas = "2.1.4.*"
numpy = ">=1.26.4,<1.27"
tqdm = ">=4.66.4,<4.67"
scikit-learn = "1.5.2.*"

[pypi-dependencies]
wandb = "*"
tianshou = "*"
gymnasium = "*"
openpyxl = "*"

[feature.cuda]
platforms = ["linux-64"]
channels = ["nvidia", {channel = "pytorch", priority = -1}]
system-requirements = {cuda = "12.1"}

[feature.cuda.dependencies]
pytorch-cuda = {version = "12.1.*", channel = "pytorch"}

[feature.cpu]
platforms = ["linux-64", "osx-64"]

[environments]
cuda = ["cuda"]
default = ["cpu"]
